"""empty message

Revision ID: 11de4a6e2c25
Revises: 68344e486674
Create Date: 2022-12-07 13:17:12.479974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11de4a6e2c25'
down_revision = '68344e486674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imgurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    op.drop_table('imgurl')
    # ### end Alembic commands ###
