"""empty message

Revision ID: 397536580f1b
Revises: bda7ad0322fe
Create Date: 2022-11-21 23:50:34.609812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397536580f1b'
down_revision = 'bda7ad0322fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_de_negocio', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('nuevo_usado', sa.String(length=80), nullable=False))
        batch_op.drop_column('procesador')

    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_de_negocio', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('nuevo_usado', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.drop_column('nuevo_usado')
        batch_op.drop_column('tipo_de_negocio')

    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procesador', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('nuevo_usado')
        batch_op.drop_column('tipo_de_negocio')

    # ### end Alembic commands ###
