"""empty message

Revision ID: 55cd3f9bfe55
Revises: b0c4fc81dd3c
Create Date: 2022-11-18 15:39:16.440681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cd3f9bfe55'
down_revision = 'b0c4fc81dd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
