"""empty message

Revision ID: b5ae13f56c09
Revises: 55cd3f9bfe55
Create Date: 2022-11-21 15:49:58.117660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ae13f56c09'
down_revision = '55cd3f9bfe55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=250), nullable=False),
    sa.Column('modelo', sa.String(length=250), nullable=False),
    sa.Column('procesador', sa.String(length=250), nullable=False),
    sa.Column('pantalla', sa.String(length=50), nullable=False),
    sa.Column('memoria_ram', sa.String(length=50), nullable=False),
    sa.Column('memoria_rom', sa.String(length=120), nullable=False),
    sa.Column('sistema_operativo', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('computadora')
    # ### end Alembic commands ###
