"""empty message

Revision ID: dcb51b4df35d
Revises: 397536580f1b
Create Date: 2022-11-22 17:26:06.459668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb51b4df35d'
down_revision = '397536580f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disco_duro', sa.String(length=50), nullable=False))
        batch_op.drop_column('memoria_rom')

    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disco_duro', sa.String(length=50), nullable=False))
        batch_op.drop_column('memoria_rom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memoria_rom', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('disco_duro')

    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memoria_rom', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('disco_duro')

    # ### end Alembic commands ###
