"""empty message

Revision ID: e6aa3a662705
Revises: 351af21464c5
Create Date: 2022-11-29 00:03:18.356657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6aa3a662705'
down_revision = '351af21464c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('moneda', sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.drop_column('moneda')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
