"""empty message

Revision ID: f7073d699644
Revises: 11de4a6e2c25
Create Date: 2022-12-07 14:12:21.384091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7073d699644'
down_revision = '11de4a6e2c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imgurl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('computadora_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('celular_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'celular', ['celular_id'], ['id'])
        batch_op.create_foreign_key(None, 'computadora', ['computadora_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imgurl', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('celular_id')
        batch_op.drop_column('computadora_id')

    # ### end Alembic commands ###
