"""empty message

Revision ID: f8ea94a377c1
Revises: a33a7786b956
Create Date: 2023-02-07 14:12:47.705728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ea94a377c1'
down_revision = 'a33a7786b956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=500), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
