"""empty message

Revision ID: f8ff6f947483
Revises: dcb51b4df35d
Create Date: 2022-11-22 20:58:27.538356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ff6f947483'
down_revision = 'dcb51b4df35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camara_frontal', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('camara_trasera', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('celular', schema=None) as batch_op:
        batch_op.drop_column('camara_trasera')
        batch_op.drop_column('camara_frontal')

    # ### end Alembic commands ###
